[webservers]
web-1    ansible_host=51.250.64.198 fqdn=fhmk7uu8h7h42c7t19rm.auto.internal
web-2    ansible_host=51.250.82.227 fqdn=fhm3aobc6sa7ljo5p8b7.auto.internal

[databases]
main    ansible_host=51.250.12.188 fqdn=fhmh5gsqaad9s7sskdhm.auto.internal
replica    ansible_host=51.250.90.177 fqdn=fhm4qok6j0tdep4nikks.auto.internal

[storage]
storage    ansible_host=51.250.10.170 fqdn=fhmsbmmfim09gf1c9epr.auto.internal
